from canva_API import code_verifier, canva_client_id, canva_secret
import requests

credentials= canva_client_id+":Zaqxsw3283!"
authorization_code = "eyJraWQiOiJlODZiMTIwMy1iMWY1LTQ4N2MtYjBiOS0yN2U0MmI2ZjMzZDkiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJlOTNiTWdONE5IUFMtbTEwNUVyXzRBIiwiY2xpZW50X2lkIjoiT0MtQVpJNVVzU21hRXFoIiwiYXVkIjoiaHR0cHM6Ly93d3cuY2FudmEuY29tIiwiaWF0IjoxNzI5MDE3Mjc3LCJuYmYiOjE3MjkwMTcyNzcsImV4cCI6MTcyOTAxNzg3NywiYnVuZGxlcyI6WyJQUk9TIl0sInRpZXIiOiJwYWlkIiwicm9sZXMiOiJtNTZyNTVnWWliU3l1d21CLUVwdGlrbjhoeWlUN2pDY1ZUb2JBX2JNWHBVUWZfWEJyVzYtYzNJeGgxQi04QVpIZWhlcHpiZldTUmNscU1PclRXUXhHU2JfOFRnS0x0RjFGd1c3NHBmczcyczBwcTJhUGd4amNCSUNXSTJJZzYycjUzbFRvaTlpd2JHZ3RmR0JyR2lEVmRrV0RlOCIsImxvY2FsZSI6InNxRkliWjhFZWt0VGVlTjBBcGRMSk5HazRZVTN2ckc2OE1SQjhHVE5nVm1KVkM1aF9GVTBxTW5famp5VmNiNGJEMkUtUnciLCJzY29wZXMiOlsiYXBwOnJlYWQiLCJhcHA6d3JpdGUiLCJkZXNpZ246Y29udGVudDpyZWFkIiwiZGVzaWduOmNvbnRlbnQ6d3JpdGUiLCJkZXNpZ246cGVybWlzc2lvbjpyZWFkIiwiZGVzaWduOnBlcm1pc3Npb246d3JpdGUiLCJhc3NldDpyZWFkIiwiYXNzZXQ6d3JpdGUiLCJicmFuZHRlbXBsYXRlOm1ldGE6cmVhZCIsImJyYW5kdGVtcGxhdGU6Y29udGVudDpyZWFkIl0sInN1YiI6Im9VVnAxRFJYS1FWMEEyRnNOQmx0STQiLCJicmFuZCI6Im9CVnAxRi1WcDE3c2pmR0hhYU9zNzgiLCJvcmdhbml6YXRpb24iOm51bGwsInBrY2UiOiJKZ21WWkFyVnl6NWRDRTRrRXdiUDNqQ2ptSHpjZW9PNWoxZGtua2VnTWw3ay04VzNSN1dMcmdERU1Rck8tSGtOalU1bGhVdkV3bVpDeC1NNi1pSFBxdVhJWFBBdWZiYTNleU5hU1JMNEZtejFJd3VDIiwicmVkaXJlY3RfdXJpIjoiaHR0cDovLzEyNy4wLjAuMTozMDAwL2NhbGxiYWNrLyJ9.2XYJZK_QuuSDddQuwlMVWqth3l9bfmrrrF-Bv3aHj8YvfAygzSQAOFKfJxkV-bLDKiXb5QHI0Ou_75EQuQy8Rg-4d6KbCUZF0-H7jHaUcU4My5o5qlbyQxVHcxFZnlFWD1ZTVaiEaMkPlR6W5UwmUBAatlO2GvAY8q11iJnW7v--iPE4oINaT5p4PcwnAVrirFiX9VML6VzGvOTcQNPEJ2U7FlHRkCT03Pkv_eQ_51y4Atc40UgDanvW8y9HEmcXSip2It4gs_oL-ZWmvgQsRp8Usqr2wI4WngrEG_5OBh2xjfsZNhmT-R7zUFxdMD6H8EcAOHtmpL6FktEyrDEHfw"

print(code_verifier)

headers = {
    "Content-Type": "application/x-www-form-urlencoded"
}

data = {
    "grant_type": "client_credentials",
    "code_verifier": code_verifier,
    "code": authorization_code,
    "redirect_uri": "http://127.0.0.1:3000/callback",
    "client_id" : canva_client_id,
    "client_secret": canva_secret
}

response = requests.post("https://api.canva.com/rest/v1/oauth/token",
    headers=headers,
    data=data
)
print(response.json())
    